---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: local
    hostname: local
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
  options:
    vvv: True
  playbooks:
    create: create.yml
verifier:
  name: ansible
